describe("Forms.js-testing inputs", function() {
    beforeEach(() => {
        cy.visit("http://localhost:3000/")
    })
    it("add text to input fields, check terms box, submit form", function() {
        cy.get("[data-cy=name]")
        .type("jeremy")
        .should("have.value", "jeremy")
        cy.get("[data-cy=email]")
        .type("example123@gmail.com")
        .should("have.value", "example123@gmail.com")
        cy.get("[data-cy=password]")
        .type("freetree87")
        .should("have.value", "freetree87")
        cy.get("[data-cy=terms]")
        .check()
        .should("be.checked")
        cy.get("[data-cy=submit]")
        .click()                
    })
})